name: eight_view_multiview
version: "3.0"
description: "8视角生成模板 v3.0 - 几何摄像机环绕范式，高成功率"
layout: "2x4_grid"
views:
  - front
  - front_right
  - right
  - back
  - left
  - front_left
  - top
  - bottom

template: |
  {output_type_description}

  This is a GEOMETRIC CAMERA ORBIT TASK, not a character redesign task.

  The subject is a STATIC OBJECT in 3D space.
  Only the CAMERA position changes.
  NO pose correction, NO aesthetic adjustment, NO reinterpretation.

  ==================================================
  ## OUTPUT LAYOUT (MANDATORY)
  Single image containing 8 panels in a 2×4 grid:
  Row 1: [FRONT 0°] [FRONT-RIGHT 45°] [RIGHT 90°] [BACK 180°]
  Row 2: [LEFT 270°] [FRONT-LEFT 315°] [TOP ↓] [BOTTOM ↑]

  No labels, no text, no markers inside the image.
  ==================================================

  ## CHARACTER DETAILS
  {character_description}

  ## STYLE REQUIREMENTS
  Style: {style}

  ## CAMERA DEFINITION (CRITICAL)

  Camera rotates around the subject at a fixed radius.
  For horizontal views (Panels 1-6): camera at eye level.
  For TOP view: camera directly above looking down.
  For BOTTOM view: camera directly below looking up.

  Camera target is the subject's center.

  The subject does NOT rotate.

  ## THE 8 REQUIRED CAMERA POSITIONS

  - Panel 1 (FRONT 0°): Camera directly in front of subject
  - Panel 2 (FRONT-RIGHT 45°): Camera at 45° to subject's right-front
  - Panel 3 (RIGHT 90°): Camera directly to subject's right side
  - Panel 4 (BACK 180°): Camera directly behind subject (NO face visible)
  - Panel 5 (LEFT 270°): Camera directly to subject's left side
  - Panel 6 (FRONT-LEFT 315°): Camera at 45° to subject's left-front
  - Panel 7 (TOP): Bird's eye view - Camera directly above, looking down at top of head
  - Panel 8 (BOTTOM): Worm's eye view - Camera directly below, looking up at soles of feet

  ==================================================
  {spatial_lock_instructions}
  ==================================================
  {top_bottom_instructions}
  ## ⚠️ LEFT vs RIGHT VIEW DISTINCTION
  
  For the RIGHT view, the camera is positioned to the right of the subject, so the subject's front points toward the LEFT edge of the image.
  For the LEFT view, the camera is positioned to the left of the subject, so the subject's front points toward the RIGHT edge of the image.

  ## BACKGROUND & ENVIRONMENT
  - Pure neutral gray or white background
  - Seamless, studio-style environment
  - No visible floor, horizon, ground texture, or stage
  - No turntable, pedestal, disc, or platform
  - Subject appears naturally grounded without visible geometry

  ## CONFIGURATION PARAMETERS
  Resolution: 4K
  Aspect Ratio: 3:2
  Sampling: deterministic (low randomness)

  ==================================================
  {final_rules_instructions}

variables:
  - character_description
  - style
  - top_bottom_instructions
  - output_type_description
  - spatial_lock_instructions
  - final_rules_instructions
